@startuml Pending Payments
participant Merchant
actor Customer
participant ProductService
participant FeedAPI
participant App
participant PE

Merchant -> ProductService: Initiate Order with ID abc


alt push
  Customer -> ProductService: submit phone number
  ProductService -> PE: Create Order
  PE -> ProductService: Return token xyz and store
  ProductService --> App: Send Push with abc
  Customer -> App: Interact
  App -> ProductService: Fetch order abc
  ProductService -> App: Return order ABC and payment token xyz
else Pull-to-refresh/Login
  Customer -> ProductService: submit phone number
  ProductService -> PE: Create Order
  PE -> ProductService: Return token xyz and store
  
...
  
  ProductService --> FeedAPI: Publish event for pending order ABC
  Customer -> App: Interact
  App -> FeedAPI: get pending orders
  FeedAPI -> App: pending order abc on service: "ProductService"
  App -> ProductService: Fetch order abc
  ProductService -> App: Return order ABC and payment token xyz

...
  
  ProductService --> FeedAPI: Publish event for pending order ABC with all data
  Customer -> App: Interact
  App -> FeedAPI: get pending orders
  FeedAPI -> App: return order abc

else appswitch
  Merchant --> App: Redirect to vipps app with order ABC
  App -> VippsPunkt: validate token
  VippsPunkt -> App: go to service XXX

  app -> PE : get payment

...

  App -> ProductService: PUT order abc with CustomerID 
  ProductService -> PE: Create Order
  PE -> ProductService: Return token xyz and store
  ProductService -> App: Return payment

  ...

  ProductService -> FeedAPI: sync api pending order ABC with all data
  ProductService -> App: Return OK
  App -> FeedAPI: get pending orders
  FeedAPI -> App: return order abc

end

App <-> ProductService: Do product things
Customer --> App: Go to payment screen
  App -> PE: GET order/<ordertoken>
  App <-- PE: Info for SCA incl. amount

loop while user interacts with order flow
  App -> ProductService: Modify order
  ProductService -> PE: POST order/
  ProductService <-- PE: ordertoken

  App <-- ProductService: ordertoken
  App -> PE: GET order/<ordertoken>
  App <-- PE: Info for SCA incl. amount
  App -> PE: Call /prepare
  App <-- PE: Surcharge etc.


  note over App, PE: Display screen for approval by user.\nSCA info (amount, merchant etc.) MUST be taken from PE.\nIn addition supplementary info from product service (delivery\nmethod; shopping cart) can be displayed from data exchanged\nwith product service.


end

App -> PE: User signs; POST payment/
App <-- PE: OK
ProductService <- PE: Notified through Event Hub\nor polling

@enduml