@startuml
hide empty description
[*] --> Created
Created : Payment created via api
Created --> Terminated
Terminated : Terminated by timeout
Terminated : Terminated by user cancellation
Terminated --> [*]
Created --> Authorised
Authorised : User has approved payment
Authorised : Defined by ""$.aggregate.authorisedAmount"" object
Authorised --> Capture
Capture : Payment fully or partially captured
Capture : Defined by ""$.aggregate.capturedAmount"" object
Capture --> Refund
Refund : Payment fully or partially refunded
Refund : Defined by ""$.aggregate.refundedAmount"" object
Refund --> [*] : Once payment is \nfully refunded
Created --> Cancel : Not possible if user is actively \nauthorising the payment
Authorised --> Cancel 
Capture --> Cancel : Not possible after \nfull capture
Cancel : Cancels the remaining un-captured amount
Cancel : Defined by ""$.aggregate.cancelledAmount"" object
Cancel --> [*]
@enduml
